site_name: PussTheCat.org
theme:
  name: material
  font: false
  palette:
    scheme: slate
copyright: Licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>
