site_name: TheFrenchGhosty's Wiki
site_url: https://wiki.thefrenchghosty.me/
site_author: TheFrenchGhosty
site_description: >-
  TheFrenchGhosty's Wiki
theme:
  name: material
  font: false
  palette:
    scheme: slate
    primary: indigo
    accent: blue
  logo: images/logo.png # https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#logo
  favicon: images/favicon.ico # https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#favicon
  features:
    - navigation.tracking # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#anchor-tracking
    - navigation.expand # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-expansion
    - navigation.top # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button
copyright: Licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TheFrenchGhosty/wiki.thefrenchghosty.me

markdown_extensions:
  - md_in_html
  - toc:
      permalink: true
      baselevel: 2
  - tables
  - pymdownx.magiclink

nav:
  - Home: index.md
  - General:
    - Things I know / Things I need to learn: general/thing-I-know-or-need-to-learn.md
    - Recipes (Vegan): general/vegan-recipes.md
  - Privacy Guide:
    - Privacy Guide: privacy-guide/privacy-guide.md
    - Privacy Guide - Email providers: privacy-guide/email-providers.md
  - Linux:
    - Encrypted Debian Install: linux/encrypted-debian-install.md
    - Linux Commands: linux/linux-commands.md
    - Arch Linux - XFCE Uninstall: linux/arch-linux-xfce-uninstall.md
    - Linux's Reserved Network Ports: linux/linux-reserved-network-ports.md
    - How to install the Nvidia 340 driver on Debian?: linux/debian-nvidia-340-driver.md
    - Testing drives with SmartCTL: linux/smartctl-tests.md
    - KVM/QEMU/Libvirt/Virt-Manager Setup (PC and Server): linux/kvm.md
    - Arch Linux - Switch to LTS kernel: linux/arch-linux-lts-kernel.md
    - How to check if you are running a vulnerable LUKS setup (LUKS key derivation function): linux/vulnerable-luks-setup.md
    - Change a machine hostname: linux/linux-change-hostname.md
    - Change a machine DNS server: linux/linux-change-dns.md
  - Android:
    - ADB Cheat Sheet: android/adb.md
  - Gaming:
    - Video Game Mods: gaming/video-game-mods.md
    - RimWorld 1.2 Modlist: gaming/rimworld-1-2-modlist.md
    - Starbound Modlist: gaming/starbound-modlist.md
  - Archive:
    - Bibliogram's Janky Setup: archive/bibliogram-janky-setup.md
